remote_theme: pages-themes/minimal@v0.2.0
title: Dineshika Karunarathna
description: An accomplished and versatile Full-Stack Software Engineer with two years of dynamic experience in the software industry. As an AWS Certified Solutions Architect – Associate, I possess robust engineering knowledge and a passion for innovative and analytical problem-solving. Highly adaptable and driven by a commitment to continuous learning and professional growth, I thrive on embracing challenges. Dedicated to delivering exceptional outcomes to the organisation, both individually and collaboratively as part of a team.
# show_downloads : true
logo: /assets/img/Profile picture.png
